######################################################################
# Automatically generated by qmake (3.0) Sun Nov 11 01:28:15 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = fribstb
INCLUDEPATH += .

# Input
SOURCES += main.cpp stb.cpp stbwidget.cpp stbfunctions.cpp jpkoconv.cpp
QT += widgets
HEADERS = stbwidget.h stbglobal.h stbfunctions.h stb.h
